refactor(feedback): better feedback for install and uninstall steps

diff --git a/bin/node-remove b/bin/node-remove
--- a/bin/node-remove
+++ b/bin/node-remove
@@ -2,50 +2,40 @@
 
 # create .czrc to specify adapter for commitizen
 if [ -f ~/.czrc ]; then
-  echo "removing  ~/.czrc"
   rm -rf ~/.czrc
   if [ $? == 0 ]; then
-    echo "command executed: rm -rf ~/.czrc"
-    echo "removed ~/.czrc"
-    echo
+    printf "\nremoved ~/.czrc\n"
   fi
 fi
 
 # uninstall awesome global node_modules
-nodeModules=('commitizen' 'cz-conventional-changelog' 'semantic-release-cli' 'greenkeeper' 'http-server'  'watch-and-rsync' 'yo' 'doctoc');
-for nodeModule in "${nodeModules[@]}"
-do
-  echo "uninstalling $nodeModule globally"
-  npm rm -g $nodeModule
-  if [ $? == 0 ]; then
-    echo "command executed: npm rm -g $nodeModule"
-    echo "uninstalled $nodeModule globally"
-    echo
-  fi
-done
+printf "\nuninstalling node-modules globally\n"
+printf "it may take few minutes ...\n"
+nodeModules="commitizen cz-conventional-changelog semantic-release-cli greenkeeper http-server watch-and-rsync yo doctoc"
+npm rm -g $nodeModules &>/dev/null
+if [ $? == 0 ]; then
+  printf "uninstalled $nodeModules globally\n"
+fi
 
 # uninstall node and n
+printf "\nsudo password might be required for removing n and node\n"
 bins=('/usr/local/bin/n' '/usr/local/bin/node');
 for bin in "${bins[@]}"
 do
   if [ -f $bin ]; then
-    echo "removing $bin"
     sudo rm -rf $bin;
     if [ $? == 0 ]; then
-      echo "command executed: sudo rm -rf $bin;"
-      echo "removed $bin"
-      echo
+      printf "removed $bin\n"
     fi
   fi
 done
 
 # delete /usr/local/n
+printf "\nsudo password might be required for removing $nDir\n"
 nDir='/usr/local/n'
 if [ -d $nDir ]; then
-  echo "removing $nDir"
   sudo rm -rf $nDir;
   if [ $? == 0 ]; then
-    echo "command executed: rm -rf $nDir;"
-    echo "removed $nDir"
+    printf "removed $nDir\n"
   fi
 fi
diff --git a/bin/node-setup b/bin/node-setup
--- a/bin/node-setup
+++ b/bin/node-setup
@@ -2,62 +2,56 @@
 
 # create directory /usr/local/n
 # n needs this directory to store the installed node versions
+printf "\nsudo password might be required for creating $nDir\n"
 nDir='/usr/local/n/versions/'
 if [ ! -d $nDir ]; then
-  echo "creating $nDir"
   sudo mkdir -p $nDir;
   if [ $? == 0 ]; then
-    echo "command executed: sudo mkdir $nDir;"
-    echo "created $nDir"
+    printf "created $nDir\n"
   fi
 fi
 
 # change owner of /usr/local/{bin,lib,n} to current user
 # to avoid installing global node_modules with sudo
+printf "\nsudo password might be required for changing owner of $localDir to $USER\n"
 localDirs=('bin' 'lib' 'n');
 for localDir in "${localDirs[@]}"
 do
   if [ -d /usr/local/$localDir ]; then
-    echo "changing owner of $localDir"
     sudo chown -R $USER /usr/local/$localDir
     if [ $? == 0 ]; then
-      echo "command executed: sudo chown $USER $localDir;"
-      echo "changed owner of $localDir"
-      echo
+      printf "changed owner of /usr/local/$localDir to $USER\n"
     fi
   fi
 done
 
 # fetch n from github and set the x flag on
+printf "\n"
 nBin=/usr/local/bin/n
-echo "fetching n"
-curl -o $nBin https://raw.githubusercontent.com/sarbbottam/n/master/bin/n
-echo "setting on the x flag"
+if [ ! -f $nBin ]; then
+  printf "fetching n at $nBin\n"
+  curl -o $nBin https://raw.githubusercontent.com/sarbbottam/n/master/bin/n
+fi
+
+printf "setting +x for $nBin\n"
 chmod 755 $nBin
 
 # install node
 n latest
 
 # install awesome global node_modules
-nodeModules=('commitizen' 'cz-conventional-changelog' 'semantic-release-cli' 'greenkeeper' 'http-server'  'watch-and-rsync' 'yo' 'doctoc');
-for nodeModule in "${nodeModules[@]}"
-do
-  echo "installing $nodeModule globally"
-  npm i -g $nodeModule
-  if [ $? == 0 ]; then
-    echo "command executed: npm i -g $nodeModule"
-    echo "installed $nodeModule globally"
-    echo
-  fi
-done
+printf "\ninstalling node-modules globally\n"
+printf "it may take few minutes ...\n"
+nodeModules="commitizen cz-conventional-changelog semantic-release-cli greenkeeper http-server watch-and-rsync yo doctoc"
+npm i -g $nodeModules &>/dev/null
+if [ $? == 0 ]; then
+  printf "installed $nodeModules globally\n"
+fi
 
 # create .czrc to specify adapter for commitizen
 if [ ! -f ~/.czrc ]; then
-  echo "creating  ~/.czrc"
   echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc
   if [ $? == 0 ]; then
-    echo "command executed: echo '{ \"path\": \"cz-conventional-changelog\" }' > ~/.czrc"
-    echo "created ~/.czrc"
-    echo
+    printf "\ncreated ~/.czrc\n"
   fi
 fi
